LigaNOS_MVC_Core/Controllers/ClassificacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LigaNOS_MVC_Core.Data;
using LigaNOS_MVC_Core.Models;
using LigaNOS_MVC_Core.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LigaNOS_MVC_Core.Controllers
{
    public class ClassificacaoController : Controller
    {
        private readonly LigaNosDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ClassificacaoController(
            LigaNosDbContext context,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }


        public IActionResult Index()
        {
            var jogos =
                (from a in _context.Jogo
                 join b in _context.Equipa on a.idHomeEquipa equals b.IdEquipa
                 join c in _context.Equipa on a.idAwayEquipa equals c.IdEquipa
                 select new
                 {
                     a.idJogo,
                     a.idLiga,
                     homeEquipa = b.Nome,
                     a.goalsHomeTeam,
                     a.goalsAwayTeam,
                     awayEquipa = c.Nome,
                     a.Data,
                     a.status
                 }
                ).Distinct().ToList();


            #region Lista de nomes das equipas na liga do user logado

            //var LigaUser = _context.Liga.Where(x => x.idUser == _userManager.GetUserId(User));

            //var todosOsNomes = new Dictionary<int, string>();

            //foreach (var liga in LigaUser)
            //{
            //    var listJogos = jogos.Where(x => x.idLiga == liga.idLiga).ToList();

            //    foreach (var item in listJogos)
            //    {
            //        todosOsNomes.Add(liga.idLiga, item.homeEquipa);
            //        todosOsNomes.Add(liga.idLiga, item.awayEquipa);
            //    }

            //    var NomesLiga = (from a in todosOsNomes
            //                     where a.Key == liga.idLiga
            //                     select new
            //                     {
            //                         a.Value,
            //                         a.Key
            //                     }
            //        ).Distinct().ToList();
            //}

            #endregion

            #region Comment

            //var todosOsNomes = new List<EquipasNaLiga>();

            //foreach (var liga in LigaUser)
            //{
            //    var listJogos = jogos.Where(x => x.idLiga == liga.idLiga).ToList();

            //foreach (var item in listJogos)
            //{
            //    todosOsNomes.Add(new EquipasNaLiga
            //    {
            //        IdLiga = liga.idLiga,
            //        Nome = item.homeEquipa
            //    });

            //    todosOsNomes.Add(new EquipasNaLiga
            //    {
            //        IdLiga = liga.idLiga,
            //        Nome = item.awayEquipa
            //    });
            //}
            //}


            #endregion

            var todosOsNomes = new List<EquipasNaLiga>();

            var classificacaoViewModel = new ClassificacaoViewModel()
            {
                ListScoreTableNomesEquipasModels = new List<ScoreTableNomesEquipasModel>(),
                ListLiga = new List<Liga>()
            };

            var userLiga = _context.Liga.Where(x => x.idUser == _userManager.GetUserId(User));

            //var ListaJogosIdLiga = new List<Jogo>();

            //var ListaJogosNome = new List<JogosNomeEquipaModel>();

            foreach (var liga in userLiga)
            {

                var listJogos = jogos.Where(x => x.idLiga == liga.idLiga).ToList();

                classificacaoViewModel.ListLiga.Add(liga);

                foreach (var item in listJogos)
                {
                    todosOsNomes.Add(new EquipasNaLiga
                    {
                        IdLiga = liga.idLiga,
                        Nome = item.homeEquipa
                    });

                    todosOsNomes.Add(new EquipasNaLiga
                    {
                        IdLiga = liga.idLiga,
                        Nome = item.awayEquipa
                    });
                }

                var NomesLiga = (from a in todosOsNomes
                                 where a.IdLiga == liga.idLiga
                                 select new
                                 {
                                     a.Nome,
                                     a.IdLiga
                                 }
                    ).Distinct().ToList();

                foreach (var nome in NomesLiga)
                {
                    int vitorias = 0, empates = 0, derrotas = 0, golosMarcados = 0, golosSofridos = 0, pontos = 0, jogosJogados = 0;

                    foreach (var item in listJogos)
                    {
                        if (item.status != false)
                        {
                            if (nome.Nome == item.homeEquipa)
                            {
                                golosMarcados += item.goalsHomeTeam;
                                golosSofridos += item.goalsAwayTeam;
                                jogosJogados += 1;

                                if (item.goalsHomeTeam > item.goalsAwayTeam)
                                {
                                    pontos += 3;
                                    vitorias += 1;
                                }
                                else if (item.goalsHomeTeam < item.goalsAwayTeam)
                                {
                                    derrotas += 1;
                                }
                                else if (item.goalsHomeTeam == item.goalsAwayTeam)
                                {
                                    pontos += 1;
                                    empates += 1;
                                }
                            }

                            if (nome.Nome == item.awayEquipa)
                            {
                                golosMarcados += item.goalsAwayTeam;
                                golosSofridos += item.goalsHomeTeam;
                                jogosJogados += 1;

                                if (item.goalsAwayTeam > item.goalsHomeTeam)
                                {
                                    pontos += 3;
                                    vitorias += 1;
                                }
                                else if (item.goalsAwayTeam < item.goalsHomeTeam)
                                {
                                    derrotas += 1;
                                }
                                else if (item.goalsAwayTeam == item.goalsHomeTeam)
                                {
                                    pontos += 1;
                                    empates += 1;
                                }
                            }
                        }
                        
                    }

                    var scoreTableNomesEquipasModel = new ScoreTableNomesEquipasModel
                    {
                        idLiga = nome.IdLiga,
                        NomeEquipa = nome.Nome,
                        JogosJogados = jogosJogados,
                        Vitorias = vitorias,
                        Empates = empates,
                        Derrotas = derrotas,
                        GolosMarcados = golosMarcados,
                        GolosSofridos = golosSofridos,
                        Pontos = pontos,
                    };

                    classificacaoViewModel.ListScoreTableNomesEquipasModels.Add(scoreTableNomesEquipasModel);
                }
            }

            var sortedList = classificacaoViewModel.ListScoreTableNomesEquipasModels.OrderByDescending(x => x.Pontos).ToList();

            classificacaoViewModel.ListScoreTableNomesEquipasModels = sortedList;

            return View(classificacaoViewModel);
        }
    }
}

LigaNOS_MVC_Core/Views/Shared/_SharedLanding.cshtml
@using Microsoft.AspNetCore.Identity
@using LigaNOS_MVC_Core.Models
@*@model LigaNOS_MVC_Core.Models.AccountViewModels.LoginViewModel*@
@model LigaNOS_MVC_Core.Models.ViewModels.SinglePageViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!doctype html>

<html lang="en">

<head>
    <title>Liga NOS</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Trabalho final do módulo.">
    <meta name="keywords" content="HTML,CSS,JavaScript, ASP.NET Core, MVC, CINEL">
    <meta name="author" content="João Ribeiro">

    <link rel="icon" href="img/favicon.png">
    <link href="~/css/reset.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.css" rel="stylesheet" />

</head>

<body data-spy="scroll" data-target=".navbar" style="position: relative">

    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <form asp-controller="Account" asp-action="Login" method="post">
                        <div class="form-group">
                            <label>Email address</label>
                            <input asp-for="LoginViewModel.Email" class="form-control" placeholder="Enter email">

                            <label>Password</label>
                            <input asp-for="LoginViewModel.Password" class="form-control" placeholder="Enter password">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Login</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="ManageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Manage Account</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <form asp-controller="Manage" asp-action="Index" method="post">
                        <div class="form-group">
                            <label style="color: gray">Email</label>
                            <input asp-for="IndexViewModel.Email" class="form-control" disabled />
                            <br />
                            <label style="color: gray">User Name</label>
                            <input asp-for="IndexViewModel.Username" class="form-control" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <form asp-controller="Account" asp-action="Register" method="post">
                        <div class="form-group">
                            <label style="color: gray">Email</label>
                            <input asp-for="RegisterViewModel.Email" class="form-control" />
                            <br />
                            <label style="color: gray">Password</label>
                            <input asp-for="RegisterViewModel.Password" class="form-control" />
                            <br />
                            <label style="color: gray">Confirm Password</label>
                            <input asp-for="RegisterViewModel.ConfirmPassword" class="form-control" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Register</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>


    <div class="row">
        <nav class="fixed-top navbar navbar-expand-lg navbar-light" id="navbar-bck">

            <a class="navbar-brand" href="#champ"><img id="logo" src="img/logo.png"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navicon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a id="homeLink" class="nav-item nav-link" href="#home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a id="equipasLink" class="nav-item nav-link" href="#clubes">Equipas</a>
                    </li>
                    <li class="nav-item">
                        <a id="jornadasLink" class="nav-item nav-link" href="#jornadas">Calendário</a>
                    </li>
                    <li class="nav-item">
                        <a id="classificacaoLink" class="nav-item nav-link" href="#classificacao">Classificação</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a asp-controller="ManageEquipas" asp-action="Index" class="nav-item nav-link">Simular</a>
                    }

                </ul>
                <br>
                <ul class="navbar-nav ml-auto">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-item nav-link" data-toggle="modal" data-target="#ManageModal">Hello @UserManager.GetUserName(User)!</a>
                        </li>
                        <li class="nav-item">
                            &nbsp;&nbsp;
                        </li>
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" id="logout" type="submit">Log out</button>
                        </form>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-item nav-link" data-toggle="modal" data-target="#LoginModal">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" data-toggle="modal" data-target="#RegisterModal">Register</a>
                        </li>
                    }
                </ul>
            </div>

        </nav>
    </div>

    <section class="background">

        <div class="row" data-paroller-factor="0.2">
            <div class="col-md-12 col-sm-12">
                <img src="img/bporto2.png" id="champ" style="transform: scale(1.1, 1.1); margin-top: 105px;" />
            </div>
        </div>

        <div class="row" data-paroller-factor="0.5">
            <div class="col-md-12 col-sm-12">
                <a href="#home"><img src="img/arrowDown.png" id="arrow" /></a>
            </div>
        </div>

        <!-- PageContents -->

        @RenderBody()

        <!-- PageContents -->


        <footer class="footerClass">
            <div class="container">
                <div class="sponsors_wrap">
                    <div class="ligaportugal">
                        <a href="http://www.ligaportugal.pt" target="_blank" title="NOS"><img src="img/footer/liga.png" alt="Liga Portugal"></a>
                    </div>
                    <div class="sponsors main"> Main Sponsor <span class="div">|</span> <a href="http://www.nos.pt/particulares/Pages/home.aspx?utm_source=LigaNOS&amp;utm_medium=FooterLogoNOS" target="_blank" title="NOS"><img src="img/footer/logo_nos_footer.png" alt="Nos"></a></div>
                    <div class="sponsors other">
                        Patrocinadores Oficiais <span class="div">|</span>
                        <a href="http://www.samsung.pt/" title="Samsung" target="_blank"><img src="img/footer/logo_samsung.png" alt="Samsung"></a>
                        <a href="https://www.eurobic.pt/" title="Eurobic" target="_blank"><img src="img/footer/logo_eurobic.png" alt="Eurobic"></a>
                        <a href="https://www.nike.com/pt/pt_pt/" title="Nike" target="_blank"><img src="img/footer/logo_nike.png" alt="Nike"></a>
                    </div>
                </div>
                <div class="copy">© 2018 <span>Liga NOS</span></div>
            </div>
            <div class="cf"></div>
        </footer>



        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q " crossorigin="anonymous "></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl " crossorigin="anonymous "></script>
        <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
        <script src="~/js/owl.carousel.js"></script>
        <script src="~/css/jquery.paroller.min.js"></script>

        <script src="~/js/script_dready.js"></script>

    </section>

</body>

</html>

LigaNOS_MVC_Core/Views/Shared/_SharedSimular.cshtml
@using Microsoft.AspNetCore.Identity
@using LigaNOS_MVC_Core.Models
@*@model LigaNOS_MVC_Core.Models.AccountViewModels.LoginViewModel*@
@*@model LigaNOS_MVC_Core.Models.ViewModels.SinglePageViewModel*@
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!doctype html>

<html lang="en">

<head>
    <title>Liga NOS</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Trabalho final do módulo.">
    <meta name="keywords" content="HTML,CSS,JavaScript, ASP.NET Core, MVC, CINEL">
    <meta name="author" content="João Ribeiro">

    <link rel="icon" href="img/favicon.png">
    <link href="~/css/reset.css" rel="stylesheet" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <link href="~/css/styles_sim.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.css" rel="stylesheet" />
</head>

<body data-spy="scroll" data-target=".navbar" style="position: relative">

    @*<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <form asp-controller="Account" asp-action="Login" method="post">
                        <div class="form-group">
                            <label>Email address</label>
                            <input asp-for="LoginViewModel.Email" class="form-control" placeholder="Enter email">

                            <label>Password</label>
                            <input asp-for="LoginViewModel.Password" class="form-control" placeholder="Enter password">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Login</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" id="ManageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Manage Account</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">

                    <form asp-controller="Manage" asp-action="Index" method="post">
                        <div class="form-group">
                            <label asp-for="IndexViewModel.Username"></label>
                            <input asp-for="IndexViewModel.Username" class="form-control" disabled />
                            <input asp-for="IndexViewModel.Email" class="form-control" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>*@


    <div class="row">
        <nav class="fixed-top navbar navbar-expand-lg navbar-light" id="navbar-bck">

            <a class="navbar-brand"><img id="logo" src="~/img/logo.png"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navicon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a asp-controller="ManageEquipas" asp-action="Index" id="homeLink" class="nav-item nav-link">Equipas</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Liga" asp-action="Index" class="nav-item nav-link">Liga</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Jogos" asp-action="Index" class="nav-item nav-link">Jogos</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Classificacao" asp-action="Index" class="nav-item nav-link">Classificações</a>
                    </li>

                </ul>
                <br>
                <ul class="navbar-nav ml-auto">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-item nav-link" data-toggle="modal" data-target="#ManageModal">Hello @UserManager.GetUserName(User)!</a>
                        </li>
                        <li class="nav-item">
                            &nbsp;&nbsp;
                        </li>
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button class="btn btn-sm btn-outline-secondary my-2 my-sm-0" id="logout" type="submit">Log out</button>
                        </form>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-item nav-link" data-toggle="modal" data-target="#LoginModal">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link">Register</a>
                        </li>
                    }
                </ul>
            </div>

        </nav>
    </div>

    <section class="background">


        @*<div class="row" data-paroller-factor="0.5">
            <div class="col-md-12 col-sm-12">
                <a href="#home"><img src="img/arrowDown.png" id="arrow" /></a>
            </div>
        </div>*@

        <!-- PageContents -->
        <div class="container">
            
            @RenderBody()
            
        </div>


        <!-- PageContents -->



        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q " crossorigin="anonymous "></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl " crossorigin="anonymous "></script>
        <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="~/js/owl.carousel.js"></script>
        <script src="~/css/jquery.paroller.min.js"></script>

        <script src="~/js/script_dready_sim.js"></script>

    </section>

</body>

</html>